sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t balajivenkat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true balajivenkat/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker"
  env: "BaluDockerreact-env"
  bucket_name: "balu-elb-us-east-1"
  bucket_path: "docker"
  on:
     branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
 
  
